package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * eoffice_config
 */
public class Config extends BaseModelObject<Long> implements Serializable {
    /**
     *
     * eoffice_config.cid
     */
    private Long cid;

    /**
     * 
     * 模块
     */
    private String module;

    /**
     * 
     * 配置key
     */
    private String ckey;

    /**
     * 
     * 配置value
     */
    private String cvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_config
     *
     * @mbg.generated Mon Nov 22 22:00:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field eoffice_config.cid
     * @return cid eoffice_config.cid
     */
    public Long getCid() {
        return cid;
    }

    /**
    eoffice_config.cid
     *
     * @param cid the value for eoffice_config.cid
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * get field 模块
     * @return module 模块
     */
    public String getModule() {
        return module;
    }

    /**
     * set filed 模块
     * @param module the value for 模块
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * get field 配置key
     * @return ckey 配置key
     */
    public String getCkey() {
        return ckey;
    }

    /**
     * set filed 配置key
     * @param ckey the value for 配置key
     */
    public void setCkey(String ckey) {
        this.ckey = ckey == null ? null : ckey.trim();
    }

    /**
     * get field 配置value
     * @return cvalue 配置value
     */
    public String getCvalue() {
        return cvalue;
    }

    /**
     * set filed 配置value
     * @param cvalue the value for 配置value
     */
    public void setCvalue(String cvalue) {
        this.cvalue = cvalue == null ? null : cvalue.trim();
    }

    @Override
    public Long valueOfKey() {
        return cid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.cid = value;
    }
}