package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;

import java.io.Serializable;

/**
 * 
 * eoffice_content_storage
 */
public class ContentStorage extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 存储ID
     */
    private Long sid;

    /**
     * 
     * 存储相对路径
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_storage
     *
     * @mbg.generated Sun Dec 19 19:32:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public Long valueOfKey() {
        return sid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.sid = value;
    }
}