package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * @author xbeeant mybatis generator
 * @version Wed Jan 19 10:09:09 CST 2022
 * eoffice_doc_template_category
 */
public class DocTemplateCategory extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 
     * 模板分类ID
     */
    private Long cid;

    /**
     * 
     * 
     * 分类名称
     */
    private String name;

    /**
     * 
     * 
     * 父分类ID
     */
    private Long pcid;

    /**
     * 
     * 
     * 支持的文件类型 逗号 『,』 分割
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_doc_template_category
     *
     * @mbg.generated Wed Jan 19 10:09:09 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 模板分类ID
     * @return cid 模板分类ID
     */
    public Long getCid() {
        return cid;
    }

    /**
     * set filed 模板分类ID
     * @param cid the value for 模板分类ID
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * get field 分类名称
     * @return name 分类名称
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 分类名称
     * @param name the value for 分类名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 父分类ID
     * @return pcid 父分类ID
     */
    public Long getPcid() {
        return pcid;
    }

    /**
     * set filed 父分类ID
     * @param pcid the value for 父分类ID
     */
    public void setPcid(Long pcid) {
        this.pcid = pcid;
    }

    /**
     * get field 支持的文件类型 逗号 『,』 分割
     * @return extension 支持的文件类型 逗号 『,』 分割
     */
    public String getExtension() {
        return extension;
    }

    /**
     * set filed 支持的文件类型 逗号 『,』 分割
     * @param extension the value for 支持的文件类型 逗号 『,』 分割
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    @Override
    public Long valueOfKey() {
        return cid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.cid = value;
    }
}