package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * @author xbeeant mybatis generator
 * @version Wed Jan 19 10:25:26 CST 2022
 * eoffice_doc_template
 */
public class DocTemplate extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 
     * 模板ID
     */
    private Long tid;

    /**
     * 
     * 
     * 分类ID
     */
    private Long cid;

    /**
     * 
     * 
     * 模板名称
     */
    private String title;

    /**
     * 
     * 
     * 存储ID
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_doc_template
     *
     * @mbg.generated Wed Jan 19 10:25:26 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 模板ID
     * @return tid 模板ID
     */
    public Long getTid() {
        return tid;
    }

    /**
     * set filed 模板ID
     * @param tid the value for 模板ID
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * get field 分类ID
     * @return cid 分类ID
     */
    public Long getCid() {
        return cid;
    }

    /**
     * set filed 分类ID
     * @param cid the value for 分类ID
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * get field 模板名称
     * @return title 模板名称
     */
    public String getTitle() {
        return title;
    }

    /**
     * set filed 模板名称
     * @param title the value for 模板名称
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * get field 存储ID
     * @return sid 存储ID
     */
    public Long getSid() {
        return sid;
    }

    /**
     * set filed 存储ID
     * @param sid the value for 存储ID
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    @Override
    public Long valueOfKey() {
        return tid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.tid = value;
    }
}