package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 * eoffice_folder
 */
public class Folder extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * ID
     */
    private Long fid;

    /**
     * 
     * 父ID
     */
    private Long pfid;

    /**
     * 
     * 目录名称
     */
    private String name;

    /**
     * 
     * 显示顺序
     */
    private Integer displayOrder;

    /**
     * 
     * 目录图标
     */
    private String icon;

    /**
     * 
     * 路径
     */
    private String path;

    /**
     * 
     * 是否删除
     */
    private Boolean deleted;

    /**
     * 
     * 删除时间
     */
    private Date deleteAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_folder
     *
     * @mbg.generated Sat Oct 30 18:23:36 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field ID
     * @return fid ID
     */
    public Long getFid() {
        return fid;
    }

    /**
     * set filed ID
     * @param fid the value for ID
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * get field 父ID
     * @return pfid 父ID
     */
    public Long getPfid() {
        return pfid;
    }

    /**
     * set filed 父ID
     * @param pfid the value for 父ID
     */
    public void setPfid(Long pfid) {
        this.pfid = pfid;
    }

    /**
     * get field 目录名称
     * @return name 目录名称
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 目录名称
     * @param name the value for 目录名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 显示顺序
     * @return displayOrder 显示顺序
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * set filed 显示顺序
     * @param displayOrder the value for 显示顺序
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * get field 目录图标
     * @return icon 目录图标
     */
    public String getIcon() {
        return icon;
    }

    /**
     * set filed 目录图标
     * @param icon the value for 目录图标
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * get field 路径
     * @return path 路径
     */
    public String getPath() {
        return path;
    }

    /**
     * set filed 路径
     * @param path the value for 路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * get field 是否删除
     * @return deleted 是否删除
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * set filed 是否删除
     * @param deleted the value for 是否删除
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * get field 删除时间
     * @return deleteAt 删除时间
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * set filed 删除时间
     * @param deleteAt the value for 删除时间
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }

    @Override
    public Long valueOfKey() {
        return fid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.fid = value;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }
}