package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import io.github.xbeeant.core.JavaBeansHelper;

import java.io.Serializable;
import java.util.List;

/**
 * @author xbeeant mybatis generator
 * @version Thu Jan 13 17:16:38 CST 2022
 * eoffice_perm
 */
public class Perm extends BaseModelObject<Long> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_perm
     *
     * @mbg.generated Thu Jan 13 17:16:38 CST 2022
     */
    private static final long serialVersionUID = 1L;
    /**
     * ID
     */
    private Long pid;
    /**
     * 目标ID
     */
    private Long targetId;
    /**
     * 资源ID
     */
    private Long rid;
    /**
     * 类型
     */
    private Integer type;
    /**
     * 下载
     */
    private Boolean download = false;
    /**
     * 编辑
     */
    private Boolean edit = false;
    /**
     * 打印
     */
    private Boolean print = false;
    /**
     * 查看
     */
    private Boolean view = false;
    /**
     * 注释
     */
    private Boolean comment = false;
    /**
     * 分享
     */
    private Boolean share = false;

    public Perm() {
    }

    public Perm(List<String> perms, Long rid, Long targetId, Integer type) {
        this.rid = rid;
        this.targetId = targetId;
        this.type = type;

        for (String perm : perms) {
            JavaBeansHelper.setter(this, perm, true);
        }
    }

    /**
     * get field ID
     *
     * @return pid ID
     */
    public Long getPid() {
        return pid;
    }

    /**
     * set filed ID
     *
     * @param pid the value for ID
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * get field 目标ID
     *
     * @return targetId 目标ID
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * set filed 目标ID
     *
     * @param targetId the value for 目标ID
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * get field 资源ID
     *
     * @return rid 资源ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * set filed 资源ID
     *
     * @param rid the value for 资源ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * get field 类型
     *
     * @return type 类型
     */
    public Integer getType() {
        return type;
    }

    /**
     * set filed 类型
     *
     * @param type the value for 类型
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * get field 下载
     *
     * @return download 下载
     */
    public Boolean getDownload() {
        return download;
    }

    /**
     * set filed 下载
     *
     * @param download the value for 下载
     */
    public void setDownload(Boolean download) {
        this.download = download;
    }

    /**
     * get field 编辑
     *
     * @return edit 编辑
     */
    public Boolean getEdit() {
        return edit;
    }

    /**
     * set filed 编辑
     *
     * @param edit the value for 编辑
     */
    public void setEdit(Boolean edit) {
        this.edit = edit;
    }

    /**
     * get field 打印
     *
     * @return print 打印
     */
    public Boolean getPrint() {
        return print;
    }

    /**
     * set filed 打印
     *
     * @param print the value for 打印
     */
    public void setPrint(Boolean print) {
        this.print = print;
    }

    /**
     * get field 查看
     *
     * @return view 查看
     */
    public Boolean getView() {
        return view;
    }

    /**
     * set filed 查看
     *
     * @param view the value for 查看
     */
    public void setView(Boolean view) {
        this.view = view;
    }

    /**
     * get field 注释
     *
     * @return comment 注释
     */
    public Boolean getComment() {
        return comment;
    }

    /**
     * set filed 注释
     *
     * @param comment the value for 注释
     */
    public void setComment(Boolean comment) {
        this.comment = comment;
    }

    /**
     * get field 分享
     *
     * @return share 分享
     */
    public Boolean getShare() {
        return share;
    }

    /**
     * set filed 分享
     *
     * @param share the value for 分享
     */
    public void setShare(Boolean share) {
        this.share = share;
    }

    @Override
    public Long valueOfKey() {
        return pid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.pid = value;
    }

    public Boolean hasPermission() {
        return this.download || this.edit || this.print || this.view || this.comment || this.share;
    }
}