package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * eoffice_resource_version
 */
public class ResourceVersion extends BaseModelObject<Long> implements Serializable {

    /**
     * 版本ID
     */
    private Long vid;

    /**
     * 资源ID
     */
    private Long rid;

    /**
     * 存储ID
     */
    private Long sid;

    /**
     * 资源名称
     */
    private String name;

    /**
     * 资源大小
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_resource_version
     *
     * @mbg.generated Sun Dec 19 22:49:46 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 版本ID
     * @return vid 版本ID
     */
    public Long getVid() {
        return vid;
    }

    /**
     * set filed 版本ID
     * @param vid the value for 版本ID
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * get field 资源ID
     * @return rid 资源ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * set filed 资源ID
     * @param rid the value for 资源ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * get field 存储ID
     * @return sid 存储ID
     */
    public Long getSid() {
        return sid;
    }

    /**
     * set filed 存储ID
     * @param sid the value for 存储ID
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * get field 资源名称
     * @return name 资源名称
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 资源名称
     * @param name the value for 资源名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 资源大小
     * @return size 资源大小
     */
    public Long getSize() {
        return size;
    }

    /**
     * set filed 资源大小
     * @param size the value for 资源大小
     */
    public void setSize(Long size) {
        this.size = size;
    }

    @Override
    public Long valueOfKey() {
        return vid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.vid = value;
    }

    /**
     * eoffice_resource_version.extension
     */
    private String extension;

    /**
     * get field eoffice_resource_version.extension
     * @return extension eoffice_resource_version.extension
     */
    public String getExtension() {
        return extension;
    }

    /**
     *    eoffice_resource_version.extension
     *
     * @param extension the value for eoffice_resource_version.extension
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }
}
