package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * eoffice_resource_attachment
 */
public class ResourceAttachment extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 附件ID
     */
    private Long aid;

    /**
     * 
     * 资源ID
     */
    private Long rid;

    /**
     * 
     * 存储ID
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_resource_attachment
     *
     * @mbg.generated Sun Dec 19 19:32:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 附件ID
     * @return aid 附件ID
     */
    public Long getAid() {
        return aid;
    }

    /**
     * set filed 附件ID
     * @param aid the value for 附件ID
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * get field 资源ID
     * @return rid 资源ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * set filed 资源ID
     * @param rid the value for 资源ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * get field 存储ID
     * @return sid 存储ID
     */
    public Long getSid() {
        return sid;
    }

    /**
     * set filed 存储ID
     * @param sid the value for 存储ID
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    @Override
    public Long valueOfKey() {
        return aid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.aid = value;
    }
}