package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;

import java.io.Serializable;
import java.util.Date;

/**
 * eoffice_resource
 *
 * @author xiaobiao
 */
public class Resource extends BaseModelObject<Long> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_resource
     *
     * @mbg.generated Sun Dec 19 19:32:06 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * ID
     */
    private Long rid;
    /**
     * 目录ID
     */
    private Long fid;
    /**
     * 文件ID
     */
    private Long sid;
    /**
     * 资源名称
     */
    private String name;
    /**
     * 资源类型
     */
    private String extension;
    /**
     * 资源大小
     */
    private Long size;
    /**
     * 显示顺序
     */
    private Integer displayOrder;
    /**
     * 存储路径
     */
    private String path;
    /**
     * 是否删除
     */
    private Boolean deleted;
    /**
     * 删除时间
     */
    private Date deleteAt;

    /**
     * get field ID
     *
     * @return rid ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * set filed ID
     *
     * @param rid the value for ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * get field 目录ID
     *
     * @return fid 目录ID
     */
    public Long getFid() {
        return fid;
    }

    /**
     * set filed 目录ID
     *
     * @param fid the value for 目录ID
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * get field 文件ID
     *
     * @return sid 文件ID
     */
    public Long getSid() {
        return sid;
    }

    /**
     * set filed 文件ID
     *
     * @param sid the value for 文件ID
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * get field 资源名称
     *
     * @return name 资源名称
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 资源名称
     *
     * @param name the value for 资源名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 资源类型
     *
     * @return extension 资源类型
     */
    public String getExtension() {
        return extension;
    }

    /**
     * set filed 资源类型
     *
     * @param extension the value for 资源类型
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * get field 资源大小
     *
     * @return size 资源大小
     */
    public Long getSize() {
        return size;
    }

    /**
     * set filed 资源大小
     *
     * @param size the value for 资源大小
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * get field 显示顺序
     *
     * @return displayOrder 显示顺序
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * set filed 显示顺序
     *
     * @param displayOrder the value for 显示顺序
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * get field 存储路径
     *
     * @return path 存储路径
     */
    public String getPath() {
        return path;
    }

    /**
     * set filed 存储路径
     *
     * @param path the value for 存储路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * get field 是否删除
     *
     * @return deleted 是否删除
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * set filed 是否删除
     *
     * @param deleted the value for 是否删除
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * get field 删除时间
     *
     * @return deleteAt 删除时间
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * set filed 删除时间
     *
     * @param deleteAt the value for 删除时间
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }

    @Override
    public Long valueOfKey() {
        return rid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.rid = value;
    }
}