package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * @author xbeeant mybatis generator
 * @version Wed Jan 12 11:56:41 CST 2022
 * eoffice_share_range
 */
public class ShareRange extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     *
     * eoffice_share_range.share_id
     */
    private Long shareId;

    /**
     * 
     *
     * eoffice_share_range.target_id
     */
    private Long targetId;

    /**
     * 
     * 
     * 类型 0 用户 1 分组
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_share_range
     *
     * @mbg.generated Wed Jan 12 11:56:41 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field eoffice_share_range.share_id
     * @return shareId eoffice_share_range.share_id
     */
    public Long getShareId() {
        return shareId;
    }

    /**
    eoffice_share_range.share_id
     *
     * @param shareId the value for eoffice_share_range.share_id
     */
    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    /**
     * get field eoffice_share_range.target_id
     * @return targetId eoffice_share_range.target_id
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
    eoffice_share_range.target_id
     *
     * @param targetId the value for eoffice_share_range.target_id
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * get field 类型 0 用户 1 分组
     * @return type 类型 0 用户 1 分组
     */
    public Integer getType() {
        return type;
    }

    /**
     * set filed 类型 0 用户 1 分组
     * @param type the value for 类型 0 用户 1 分组
     */
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public Long valueOfKey() {
        return shareId;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.shareId = value;
    }
}