package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * @author xbeeant mybatis generator
 * @version Mon Feb 21 19:14:17 CST 2022
 * eoffice_slave
 */
public class Slave extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     *
     * eoffice_slave.id
     */
    private Long id;

    /**
     * 
     *
     * eoffice_slave.name
     */
    private String name;

    /**
     * 
     *
     * eoffice_slave.entry
     */
    private String entry;

    /**
     * 
     *
     * eoffice_slave.container
     */
    private String container;

    /**
     * 
     *
     * eoffice_slave.active_rule
     */
    private String activeRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_slave
     *
     * @mbg.generated Mon Feb 21 19:14:17 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field eoffice_slave.id
     * @return id eoffice_slave.id
     */
    public Long getId() {
        return id;
    }

    /**
    eoffice_slave.id
     *
     * @param id the value for eoffice_slave.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field eoffice_slave.name
     * @return name eoffice_slave.name
     */
    public String getName() {
        return name;
    }

    /**
    eoffice_slave.name
     *
     * @param name the value for eoffice_slave.name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field eoffice_slave.entry
     * @return entry eoffice_slave.entry
     */
    public String getEntry() {
        return entry;
    }

    /**
    eoffice_slave.entry
     *
     * @param entry the value for eoffice_slave.entry
     */
    public void setEntry(String entry) {
        this.entry = entry == null ? null : entry.trim();
    }

    /**
     * get field eoffice_slave.container
     * @return container eoffice_slave.container
     */
    public String getContainer() {
        return container;
    }

    /**
    eoffice_slave.container
     *
     * @param container the value for eoffice_slave.container
     */
    public void setContainer(String container) {
        this.container = container == null ? null : container.trim();
    }

    /**
     * get field eoffice_slave.active_rule
     * @return activeRule eoffice_slave.active_rule
     */
    public String getActiveRule() {
        return activeRule;
    }

    /**
    eoffice_slave.active_rule
     *
     * @param activeRule the value for eoffice_slave.active_rule
     */
    public void setActiveRule(String activeRule) {
        this.activeRule = activeRule == null ? null : activeRule.trim();
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}