package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * eoffice_storage
 */
public class Storage extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     * 文件ID
     */
    private Long aid;

    /**
     * 
     * 名称
     */
    private String name;

    /**
     * 
     * 文件大小
     */
    private Long size;

    /**
     * 
     * 文件MD5
     */
    private String md5;

    /**
     * 
     * 文件扩展名
     */
    private String extension;

    /**
     * 
     * 存储相对路径
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_storage
     *
     * @mbg.generated Thu Nov 04 17:29:30 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field 文件ID
     * @return aid 文件ID
     */
    public Long getAid() {
        return aid;
    }

    /**
     * set filed 文件ID
     * @param aid the value for 文件ID
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * get field 名称
     * @return name 名称
     */
    public String getName() {
        return name;
    }

    /**
     * set filed 名称
     * @param name the value for 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get field 文件大小
     * @return size 文件大小
     */
    public Long getSize() {
        return size;
    }

    /**
     * set filed 文件大小
     * @param size the value for 文件大小
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * get field 文件MD5
     * @return md5 文件MD5
     */
    public String getMd5() {
        return md5;
    }

    /**
     * set filed 文件MD5
     * @param md5 the value for 文件MD5
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * get field 文件扩展名
     * @return extension 文件扩展名
     */
    public String getExtension() {
        return extension;
    }

    /**
     * set filed 文件扩展名
     * @param extension the value for 文件扩展名
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * get field 存储相对路径
     * @return path 存储相对路径
     */
    public String getPath() {
        return path;
    }

    /**
     * set filed 存储相对路径
     * @param path the value for 存储相对路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    @Override
    public Long valueOfKey() {
        return aid;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.aid = value;
    }
}