package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 *
 * @author xbeeant mybatis generator
 * @version Thu Mar 03 08:41:11 CST 2022
 * eoffice_user_log
 */
public class UserLog extends BaseModelObject<Long> implements Serializable {
    /**
     *
     *
     * eoffice_user_log.id
     */
    private Long id;

    /**
     *
     *
     * 用户名
     */
    private String username;

    /**
     *
     *
     * 用户昵称
     */
    private String nickname;

    /**
     *
     *
     * IP
     */
    private String ip;

    /**
     *
     *
     * 客户端agent
     */
    private String userAgent;

    /**
     *
     *
     * 用户行为（增删改查等）
     */
    private String behavior;

    /**
     *
     *
     * 资源ID
     */
    private Long rid;

    /**
     *
     *
     * 操作的表
     */
    private String objectType;

    /**
     *
     *
     * 操作的表主键
     */
    private String objectKey;

    /**
     *
     *
     * 其他
     */
    private String extra;

    /**
     *
     *
     * 操作结果（文件夹、文件等）
     */
    private String target;

    /**
     *
     *
     * 行为日志
     */
    private String log;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_user_log
     *
     * @mbg.generated Thu Mar 03 08:41:11 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field eoffice_user_log.id
     * @return id eoffice_user_log.id
     */
    public Long getId() {
        return id;
    }

    /**
     eoffice_user_log.id
     *
     * @param id the value for eoffice_user_log.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field 用户名
     * @return username 用户名
     */
    public String getUsername() {
        return username;
    }

    /**
     * set filed 用户名
     * @param username the value for 用户名
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * get field 用户昵称
     * @return nickname 用户昵称
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * set filed 用户昵称
     * @param nickname the value for 用户昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * get field IP
     * @return ip IP
     */
    public String getIp() {
        return ip;
    }

    /**
     * set filed IP
     * @param ip the value for IP
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * get field 客户端agent
     * @return userAgent 客户端agent
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * set filed 客户端agent
     * @param userAgent the value for 客户端agent
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * get field 用户行为（增删改查等）
     * @return behavior 用户行为（增删改查等）
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * set filed 用户行为（增删改查等）
     * @param behavior the value for 用户行为（增删改查等）
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * get field 资源ID
     * @return rid 资源ID
     */
    public Long getRid() {
        return rid;
    }

    /**
     * set filed 资源ID
     * @param rid the value for 资源ID
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * get field 操作的表
     * @return objectType 操作的表
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * set filed 操作的表
     * @param objectType the value for 操作的表
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * get field 操作的表主键
     * @return objectKey 操作的表主键
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * set filed 操作的表主键
     * @param objectKey the value for 操作的表主键
     */
    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey == null ? null : objectKey.trim();
    }

    /**
     * get field 其他
     * @return extra 其他
     */
    public String getExtra() {
        return extra;
    }

    /**
     * set filed 其他
     * @param extra the value for 其他
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * get field 操作结果（文件夹、文件等）
     * @return target 操作结果（文件夹、文件等）
     */
    public String getTarget() {
        return target;
    }

    /**
     * set filed 操作结果（文件夹、文件等）
     * @param target the value for 操作结果（文件夹、文件等）
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * get field 行为日志
     * @return log 行为日志
     */
    public String getLog() {
        return log;
    }

    /**
     * set filed 行为日志
     * @param log the value for 行为日志
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}