package io.github.xbeeant.eoffice.model;

import io.github.xbeeant.core.BaseModelObject;
import java.io.Serializable;

/**
 * 
 * @author xbeeant mybatis generator
 * @version Thu Jan 13 09:19:05 CST 2022
 * eoffice_user_group
 */
public class UserGroup extends BaseModelObject<Long> implements Serializable {
    /**
     * 
     *
     * eoffice_user_group.id
     */
    private Long id;

    /**
     * 
     * 
     * 用户ID
     */
    private Long uid;

    /**
     * 
     * 
     * 分组ID
     */
    private Long gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eoffice_user_group
     *
     * @mbg.generated Thu Jan 13 09:19:05 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * get field eoffice_user_group.id
     * @return id eoffice_user_group.id
     */
    public Long getId() {
        return id;
    }

    /**
    eoffice_user_group.id
     *
     * @param id the value for eoffice_user_group.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get field 用户ID
     * @return uid 用户ID
     */
    public Long getUid() {
        return uid;
    }

    /**
     * set filed 用户ID
     * @param uid the value for 用户ID
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * get field 分组ID
     * @return gid 分组ID
     */
    public Long getGid() {
        return gid;
    }

    /**
     * set filed 分组ID
     * @param gid the value for 分组ID
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    @Override
    public Long valueOfKey() {
        return id;
    }

    @Override
    public void assignKeyValue(Long value) {
        this.id = value;
    }
}