server:
  servlet:
    context-path: /eoffice
    session:
      cookie:
        path: /
  port: 8080
mybatis:
  mapper-locations: classpath*:/mybatis/mysql/eoffice/**/*.xml
  type-aliases-package: io.github.xbeeant.eoffice.model

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/eoffice?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: localhost,127.0.0.1,10.113.10.2, 10.112.73.220
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.100
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 1qUITtNS7ZPDHiJ8
      filter:
        wall:
          config:
            multi-statement-allow: true
            delete-where-none-check: true
            update-where-none-check: true
          enabled: true
      test-while-idle: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
    # 6个小时
    timeout: 21600
  jackson:
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    # 不为空的属性才会序列化,具体属性可看JsonInclude.Include
    default-property-inclusion: NON_NULL
    # 全局日期返回格式设置@JsonFormat的格式pattern
    date-format: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

debug: true

rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnXqOXXLab0GqNuw8KZ4Cro3ap1qWeYaJIisfAhC6jRe6qtWPvJiJhbOqWi8cE+Xk+OSFQfSu6MVSJI+oNo7lO94raw+/x14a6Cv+x7EGCb27JNaG+TvLYCWUg1NlivqVgSuhfuHbT1gP2oLIsaKfbCJzDImtXCMc2otHKnjx1uSWkKInzKXp5aDkXStPbRh5v/Tcvbq1Oa0E6Gs1CkUYFO3ck3QAzS/jNwhljlLGpZRcaH44+5TjP6AGGUcRYkCZ99eyIAiQIBmzGuW2WerjSmVqIbrysbdEl/CjLeJZV7zRGXZs+4wufhgQ4bl/wXzVBB+83C+WkjpqwVu3PGYgPwIDAQAB
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCdeo5dctpvQao27DwpngKujdqnWpZ5hokiKx8CELqNF7qq1Y+8mImFs6paLxwT5eT45IVB9K7oxVIkj6g2juU73itrD7/HXhroK/7HsQYJvbsk1ob5O8tgJZSDU2WK+pWBK6F+4dtPWA/agsixop9sInMMia1cIxzai0cqePHW5JaQoifMpenloORdK09tGHm/9Ny9urU5rQToazUKRRgU7dyTdADNL+M3CGWOUsallFxofjj7lOM/oAYZRxFiQJn317IgCJAgGbMa5bZZ6uNKZWohuvKxt0SX8KMt4llXvNEZdmz7jC5+GBDhuX/BfNUEH7zcL5aSOmrBW7c8ZiA/AgMBAAECggEBAJql6z779mUBwE2VanOYN5wBtHNas6D+LJeAb0AQ+5Jpdigj97bGuW6yhJ1x3AnyXwzJJdAioM34UPWUmiWR6K4FPPAzlCsOUDAmXFrwjjRsvWaswfnp7Ywq+5CICpUUBlPGbB71X/CoU1FL1BkV0adYoVDzt2pfFQvNcQLVqPFVEfVMzne4XLJhdS1YWoZj3LeWIctP1FGsM1fbAKX8THiEmqYtdeNonGA5xgIGp9MhPwtg1hIWbP1DppfxvaUr6lwKOeiMDwxmYqMa32BNLcXbbjFmGHm1lEh2FAnU7INAQDhvIru0EMPdGnNH7urCUFmiKnC7di1AvY6wjFx2uQECgYEA9VfGqSVnf6C4CMeRX++k1cSYQqLM3fdRgo8Qs9tb1wPNSymobcpYIqtMIZfo1D3AGC7nf/NrQr1ZJNMpFUbYVtNRITGMO7R5Sa69IsBRhQzT8DIgtzCV6xWnImRWwsUvQF7Da6s0XtHB1IoIPqET2UzyG258OCjXrmzfFiI+AL8CgYEApFG6EjcoP/GRh4VNeA2T5SugqaTtsPCtdBW3LsgReIM7Gj4bmuY9wLm5j0nwTUXR1Nrsm3M7ZiQ73MLFxfOBPngVJYTdwsePqV+xwtilr82HJmi+602WUUt7KZrMtJ2BJzDIjz8Pjf5v1bmBlcLWik/XAA7ggAAZwPlox8sIQIECgYEAxIbQYtPMiUajxJygDdo4DuiREue39aHUECIrvfbcJWstOqUe/vtUCElxDYPTBJiGVJjV5f+GDwr/6mifgyShzUMuvMkkzPqvIV+wr7KgWlTBPKna3QM1Q/+vRvRbL1+mjwiZv5h/teiOPINpQUnkTW++jEy/gnjs9BLPzLoXMp8CgYEAighxY03cTOLTmmE7c4cMXu3oN7npRcLYInT/fZfpPTAYHPJhZBzXcSdTHnBBIdht7P2+1tLU6fe0Jb2kP6ZPQrfDI9JaK35SSzis7f3qKSVgy74f6zAw/reGjauRHIRW8yICyHpzyZccQRBlL/YNHQD2ngDhTAVJnRamk3cVxoECgYBjSfuKXyZpZGNGncQNZzQJlyJ6bqciCVcPUSxnQCuIbuMmlNyqqkPVTiaeaXO8TmgL2lZjzSIomyW1ntVUXFMuacHQQcQ0O9YjAQISvW2ye7u98pJb+oUjcZ4y6SQyAduLYRCqYKN7W3eK/qjmER23nJDmMDZjzIsz7J5ClA5iJA==

logging:
  config: classpath:log4j2.yml
onlyoffice:
  server: http://localhost:8080
  download: eoffice/
  callback-url: eoffice/api/office/callback
  changes-url: eoffice/api/office/changes
  document-url: eoffice/api/resource/s
