server:
  servlet:
    context-path: /eoffice
    session:
      cookie:
        path: /
  port: 8080
mybatis:
  mapper-locations: classpath*:/mybatis/mysql/eoffice/**/*.xml
  type-aliases-package: io.github.xbeeant.eoffice.model

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/eoffice?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: localhost,127.0.0.1,10.113.10.2, 10.112.73.220
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.100
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 1qUITtNS7ZPDHiJ8
      filter:
        wall:
          config:
            multi-statement-allow: true
            delete-where-none-check: true
            update-where-none-check: true
          enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
    # 6个小时
    timeout: 21600
  jackson:
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    # 不为空的属性才会序列化,具体属性可看JsonInclude.Include
    default-property-inclusion: NON_NULL
    # 全局日期返回格式设置@JsonFormat的格式pattern
    date-format: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

debug: true

logging:
  config: classpath:log4j2.yml
